[build]
  publish = "."
  command = ""

[functions]
  directory = "netlify/functions"
  node_bundler = "esbuild"

[[redirects]]
  from = "/api/students"
  to = "/.netlify/functions/students"
  status = 200

[[redirects]]
  from = "/api/students/*"
  to = "/.netlify/functions/students"
  status = 200

[[redirects]]
  from = "/api/pending"
  to = "/.netlify/functions/pending"
  status = 200

[[redirects]]
  from = "/api/pending/*"
  to = "/.netlify/functions/pending"
  status = 200

[[redirects]]
  from = "/api/messages"
  to = "/.netlify/functions/messages"
  status = 200

[[redirects]]
  from = "/api/messages/*"
  to = "/.netlify/functions/messages"
  status = 200

[[redirects]]
  from = "/api/admin-login"
  to = "/.netlify/functions/admin-login"
  status = 200
